import type { ProjectConfig, Talent } from "@/types/talent";

/**
 * Mock talents (Phase 1).
 *
 * Distribution:
 *   • 30 total → 15 men + 15 women
 *   • Age buckets balanced: 20s = 7, 30s = 8, 40s = 8, 50s = 7
 *   • Categories: 5 talents each → corporativo, lifestyle, familiar, urbano, senior, oficios
 *
 * Codes follow the pattern YE-W## (women) / YE-M## (men). Numbers are intentionally
 * non-sequential to feel like a real curated catalog, not a database dump.
 */
export const TALENTS: Talent[] = [
  // ── 20s ──
  {
    code: "YE-W07",
    name: { es: "Joven entusiasta", en: "Bright newcomer" },
    shortDesc: { es: "Mujer · 22-26 · Energía", en: "Woman · 22-26 · Energy" },
    gender: "f",
    ageRange: "22-26",
    ageBucket: "20s",
    phenotype: { es: "Latina mestiza", en: "Latina mestiza" },
    archetype: { es: "Energía emergente", en: "Emerging energy" },
    category: "urbano",
    toneCommercial: { es: "Casual aspiracional", en: "Casual aspirational" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Tech / electrónica", en: "Tech / electronics" },
      { es: "Retail joven", en: "Young retail" },
      { es: "Streaming / OTT", en: "Streaming / OTT" },
    ],
    status: "available",
    hue: 340,
    sat: 45,
  },
  {
    code: "YE-M16",
    name: { es: "Estudiante universitario", en: "University student" },
    shortDesc: { es: "Hombre · 19-23 · Joven", en: "Man · 19-23 · Young" },
    gender: "m",
    ageRange: "19-23",
    ageBucket: "20s",
    phenotype: { es: "Latino mestizo", en: "Latino mestizo" },
    archetype: { es: "Joven en formación", en: "Young in training" },
    category: "urbano",
    toneCommercial: { es: "Cotidiano cercano", en: "Everyday close" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Universidades", en: "Universities" },
      { es: "Telco / planes", en: "Telco / plans" },
      { es: "Banca digital", en: "Digital banking" },
    ],
    status: "available",
    hue: 170,
    sat: 30,
  },
  {
    code: "YE-W11",
    name: { es: "Creativa independiente", en: "Independent creative" },
    shortDesc: { es: "Mujer · 24-28 · Editorial", en: "Woman · 24-28 · Editorial" },
    gender: "f",
    ageRange: "24-28",
    ageBucket: "20s",
    phenotype: { es: "Mestiza europea", en: "Mixed European" },
    archetype: { es: "Creadora urbana", en: "Urban creator" },
    category: "urbano",
    toneCommercial: { es: "Editorial cool", en: "Editorial cool" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Moda / lifestyle", en: "Fashion / lifestyle" },
      { es: "Tech / electrónica", en: "Tech / electronics" },
    ],
    status: "available",
    hue: 280,
    sat: 38,
  },
  {
    code: "YE-M14",
    name: { es: "Urbano creativo", en: "Urban creative" },
    shortDesc: { es: "Hombre · 26-32 · Editorial", en: "Man · 26-32 · Editorial" },
    gender: "m",
    ageRange: "26-32",
    ageBucket: "20s",
    phenotype: { es: "Latino mestizo", en: "Latino mestizo" },
    archetype: { es: "Editorial urbano", en: "Urban editorial" },
    category: "urbano",
    toneCommercial: { es: "Premium contenido", en: "Premium content" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Moda masculina", en: "Menswear" },
      { es: "Streaming", en: "Streaming" },
      { es: "Tech aspiracional", en: "Aspirational tech" },
    ],
    status: "available",
    hue: 220,
    sat: 25,
  },
  {
    code: "YE-W19",
    name: { es: "Profesional emergente", en: "Emerging professional" },
    shortDesc: { es: "Mujer · 24-28 · Corporativa", en: "Woman · 24-28 · Corporate" },
    gender: "f",
    ageRange: "24-28",
    ageBucket: "20s",
    phenotype: { es: "Latina mestiza", en: "Latina mestiza" },
    archetype: { es: "Profesional confiable", en: "Trustworthy professional" },
    category: "corporativo",
    toneCommercial: { es: "Confiable contenido", en: "Trustworthy content" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Banca", en: "Banking" },
      { es: "Servicios B2B", en: "B2B services" },
      { es: "Seguros", en: "Insurance" },
    ],
    status: "available",
    hue: 35,
    sat: 28,
  },
  {
    code: "YE-M22",
    name: { es: "Lifestyle aspiracional", en: "Aspirational lifestyle" },
    shortDesc: { es: "Hombre · 25-29 · Premium", en: "Man · 25-29 · Premium" },
    gender: "m",
    ageRange: "25-29",
    ageBucket: "20s",
    phenotype: { es: "Latino europeizado", en: "Europeanized Latino" },
    archetype: { es: "Lifestyle premium", en: "Premium lifestyle" },
    category: "lifestyle",
    toneCommercial: { es: "Premium aspiracional", en: "Premium aspirational" },
    market: ["CL", "LATAM", "US"],
    suggestedUses: [
      { es: "Automotriz", en: "Automotive" },
      { es: "Banca premium", en: "Premium banking" },
      { es: "Inmobiliaria", en: "Real estate" },
    ],
    status: "available",
    hue: 25,
    sat: 22,
  },
  {
    code: "YE-W28",
    name: { es: "Lifestyle citadina", en: "City lifestyle" },
    shortDesc: { es: "Mujer · 23-27 · Cotidiano", en: "Woman · 23-27 · Everyday" },
    gender: "f",
    ageRange: "23-27",
    ageBucket: "20s",
    phenotype: { es: "Mestiza", en: "Mixed" },
    archetype: { es: "Lifestyle citadina", en: "City lifestyle" },
    category: "lifestyle",
    toneCommercial: { es: "Cercano premium", en: "Close premium" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Retail aspiracional", en: "Aspirational retail" },
      { es: "Bebidas", en: "Beverages" },
      { es: "Telco", en: "Telco" },
    ],
    status: "in-campaign",
    hue: 12,
    sat: 32,
  },

  // ── 30s ──
  {
    code: "YE-W03",
    name: { es: "Ejecutiva contemporánea", en: "Contemporary executive" },
    shortDesc: { es: "Mujer · 32-38 · Premium", en: "Woman · 32-38 · Premium" },
    gender: "f",
    ageRange: "32-38",
    ageBucket: "30s",
    phenotype: { es: "Latina mestiza", en: "Latina mestiza" },
    archetype: { es: "Profesional aspiracional", en: "Aspirational professional" },
    category: "corporativo",
    toneCommercial: { es: "Premium contenido", en: "Premium content" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Banca premium", en: "Premium banking" },
      { es: "Tech / electrónica", en: "Tech / electronics" },
      { es: "Retail aspiracional", en: "Aspirational retail" },
      { es: "Automotriz", en: "Automotive" },
      { es: "Servicios B2B", en: "B2B services" },
    ],
    status: "available",
    hue: 18,
    sat: 35,
  },
  {
    code: "YE-M09",
    name: { es: "Ejecutivo emergente", en: "Emerging executive" },
    shortDesc: { es: "Hombre · 32-38 · Aspiracional", en: "Man · 32-38 · Aspirational" },
    gender: "m",
    ageRange: "32-38",
    ageBucket: "30s",
    phenotype: { es: "Latino europeizado", en: "Europeanized Latino" },
    archetype: { es: "Ejecutivo joven", en: "Young executive" },
    category: "corporativo",
    toneCommercial: { es: "Premium contenido", en: "Premium content" },
    market: ["CL", "LATAM", "US"],
    suggestedUses: [
      { es: "Banca", en: "Banking" },
      { es: "Tecnología B2B", en: "B2B technology" },
      { es: "Consultoría", en: "Consulting" },
    ],
    status: "available",
    hue: 25,
    sat: 30,
  },
  {
    code: "YE-W22",
    name: { es: "Madre profesional", en: "Working mother" },
    shortDesc: { es: "Mujer · 35-42 · Familiar", en: "Woman · 35-42 · Family" },
    gender: "f",
    ageRange: "35-42",
    ageBucket: "30s",
    phenotype: { es: "Latina mestiza", en: "Latina mestiza" },
    archetype: { es: "Madre activa", en: "Active mother" },
    category: "familiar",
    toneCommercial: { es: "Cotidiano premium", en: "Premium everyday" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Retail familiar", en: "Family retail" },
      { es: "Banca", en: "Banking" },
      { es: "Salud", en: "Health" },
    ],
    status: "available",
    hue: 8,
    sat: 40,
  },
  {
    code: "YE-W18",
    name: { es: "Madre milenial", en: "Millennial mother" },
    shortDesc: { es: "Mujer · 28-34 · Cotidiano", en: "Woman · 28-34 · Everyday" },
    gender: "f",
    ageRange: "28-34",
    ageBucket: "30s",
    phenotype: { es: "Mestiza", en: "Mixed" },
    archetype: { es: "Madre joven moderna", en: "Modern young mother" },
    category: "familiar",
    toneCommercial: { es: "Cotidiano cercano", en: "Close everyday" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Retail familiar", en: "Family retail" },
      { es: "Alimentación", en: "Food" },
      { es: "Hogar", en: "Home" },
    ],
    status: "available",
    hue: 350,
    sat: 35,
  },
  {
    code: "YE-M21",
    name: { es: "Padre joven", en: "Young father" },
    shortDesc: { es: "Hombre · 30-36 · Familiar", en: "Man · 30-36 · Family" },
    gender: "m",
    ageRange: "30-36",
    ageBucket: "30s",
    phenotype: { es: "Latino mestizo", en: "Latino mestizo" },
    archetype: { es: "Padre presente", en: "Present father" },
    category: "familiar",
    toneCommercial: { es: "Cotidiano cercano", en: "Close everyday" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Hogar", en: "Home" },
      { es: "Automotriz", en: "Automotive" },
      { es: "Seguros", en: "Insurance" },
    ],
    status: "available",
    hue: 30,
    sat: 25,
  },
  {
    code: "YE-W12",
    name: { es: "Lifestyle wellness", en: "Wellness lifestyle" },
    shortDesc: { es: "Mujer · 30-36 · Bienestar", en: "Woman · 30-36 · Wellness" },
    gender: "f",
    ageRange: "30-36",
    ageBucket: "30s",
    phenotype: { es: "Latina europeizada", en: "Europeanized Latina" },
    archetype: { es: "Wellness urbana", en: "Urban wellness" },
    category: "lifestyle",
    toneCommercial: { es: "Premium contenido", en: "Premium content" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Belleza", en: "Beauty" },
      { es: "Wellness", en: "Wellness" },
      { es: "Salud premium", en: "Premium health" },
    ],
    status: "available",
    hue: 145,
    sat: 28,
  },
  {
    code: "YE-M05",
    name: { es: "Profesional balanceado", en: "Balanced professional" },
    shortDesc: { es: "Hombre · 33-39 · Lifestyle", en: "Man · 33-39 · Lifestyle" },
    gender: "m",
    ageRange: "33-39",
    ageBucket: "30s",
    phenotype: { es: "Latino mestizo", en: "Latino mestizo" },
    archetype: { es: "Lifestyle balanceado", en: "Balanced lifestyle" },
    category: "lifestyle",
    toneCommercial: { es: "Aspiracional cercano", en: "Close aspirational" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Banca", en: "Banking" },
      { es: "Automotriz", en: "Automotive" },
      { es: "Tech", en: "Tech" },
    ],
    status: "available",
    hue: 200,
    sat: 22,
  },
  {
    code: "YE-M27",
    name: { es: "Tech enthusiast", en: "Tech enthusiast" },
    shortDesc: { es: "Hombre · 31-37 · Innovador", en: "Man · 31-37 · Innovator" },
    gender: "m",
    ageRange: "31-37",
    ageBucket: "30s",
    phenotype: { es: "Mestizo europeizado", en: "Europeanized mixed" },
    archetype: { es: "Innovador tech", en: "Tech innovator" },
    category: "urbano",
    toneCommercial: { es: "Editorial premium", en: "Premium editorial" },
    market: ["CL", "LATAM", "US"],
    suggestedUses: [
      { es: "Tech / electrónica", en: "Tech / electronics" },
      { es: "Streaming", en: "Streaming" },
      { es: "Apps / fintech", en: "Apps / fintech" },
    ],
    status: "available",
    hue: 195,
    sat: 35,
  },
  {
    code: "YE-W25",
    name: { es: "Maestra contemporánea", en: "Contemporary teacher" },
    shortDesc: { es: "Mujer · 30-36 · Educadora", en: "Woman · 30-36 · Educator" },
    gender: "f",
    ageRange: "30-36",
    ageBucket: "30s",
    phenotype: { es: "Latina mestiza", en: "Latina mestiza" },
    archetype: { es: "Educadora cercana", en: "Approachable educator" },
    category: "oficios",
    toneCommercial: { es: "Cotidiano confiable", en: "Trustworthy everyday" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Educación", en: "Education" },
      { es: "Servicios públicos", en: "Public services" },
      { es: "Banca cercana", en: "Community banking" },
    ],
    status: "available",
    hue: 165,
    sat: 30,
  },

  // ── 40s ──
  {
    code: "YE-W30",
    name: { es: "Ejecutiva senior", en: "Senior executive" },
    shortDesc: { es: "Mujer · 45-52 · Liderazgo", en: "Woman · 45-52 · Leadership" },
    gender: "f",
    ageRange: "45-52",
    ageBucket: "40s",
    phenotype: { es: "Latina europeizada", en: "Europeanized Latina" },
    archetype: { es: "Líder ejecutiva", en: "Executive leader" },
    category: "corporativo",
    toneCommercial: { es: "Autoridad premium", en: "Premium authority" },
    market: ["CL", "LATAM", "US"],
    suggestedUses: [
      { es: "Banca corporativa", en: "Corporate banking" },
      { es: "Consultoría", en: "Consulting" },
      { es: "Seguros premium", en: "Premium insurance" },
    ],
    status: "available",
    hue: 250,
    sat: 25,
  },
  {
    code: "YE-M11",
    name: { es: "Director estratégico", en: "Strategic director" },
    shortDesc: { es: "Hombre · 42-48 · Liderazgo", en: "Man · 42-48 · Leadership" },
    gender: "m",
    ageRange: "42-48",
    ageBucket: "40s",
    phenotype: { es: "Latino europeizado", en: "Europeanized Latino" },
    archetype: { es: "Director estratégico", en: "Strategic director" },
    category: "corporativo",
    toneCommercial: { es: "Autoridad confiable", en: "Trustworthy authority" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Banca corporativa", en: "Corporate banking" },
      { es: "B2B premium", en: "Premium B2B" },
      { es: "Inversiones", en: "Investments" },
    ],
    status: "available",
    hue: 215,
    sat: 18,
  },
  {
    code: "YE-W17",
    name: { es: "Madre experimentada", en: "Experienced mother" },
    shortDesc: { es: "Mujer · 42-48 · Familiar", en: "Woman · 42-48 · Family" },
    gender: "f",
    ageRange: "42-48",
    ageBucket: "40s",
    phenotype: { es: "Latina mestiza", en: "Latina mestiza" },
    archetype: { es: "Madre referente", en: "Reference mother" },
    category: "familiar",
    toneCommercial: { es: "Cotidiano premium", en: "Premium everyday" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Retail familiar", en: "Family retail" },
      { es: "Salud", en: "Health" },
      { es: "Hogar", en: "Home" },
    ],
    status: "available",
    hue: 15,
    sat: 28,
  },
  {
    code: "YE-M19",
    name: { es: "Padre presente", en: "Engaged father" },
    shortDesc: { es: "Hombre · 42-48 · Familiar", en: "Man · 42-48 · Family" },
    gender: "m",
    ageRange: "42-48",
    ageBucket: "40s",
    phenotype: { es: "Latino mestizo", en: "Latino mestizo" },
    archetype: { es: "Padre referente", en: "Reference father" },
    category: "familiar",
    toneCommercial: { es: "Cotidiano confiable", en: "Trustworthy everyday" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Hogar", en: "Home" },
      { es: "Banca familiar", en: "Family banking" },
      { es: "Automotriz", en: "Automotive" },
    ],
    status: "available",
    hue: 35,
    sat: 22,
  },
  {
    code: "YE-W08",
    name: { es: "Lifestyle plena", en: "Confident lifestyle" },
    shortDesc: { es: "Mujer · 41-47 · Refinada", en: "Woman · 41-47 · Refined" },
    gender: "f",
    ageRange: "41-47",
    ageBucket: "40s",
    phenotype: { es: "Latina europeizada", en: "Europeanized Latina" },
    archetype: { es: "Lifestyle plena", en: "Confident lifestyle" },
    category: "lifestyle",
    toneCommercial: { es: "Premium aspiracional", en: "Aspirational premium" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Inmobiliaria premium", en: "Premium real estate" },
      { es: "Belleza madura", en: "Mature beauty" },
      { es: "Banca premium", en: "Premium banking" },
    ],
    status: "reserved",
    hue: 295,
    sat: 22,
  },
  {
    code: "YE-M24",
    name: { es: "Profesional artesano", en: "Artisan professional" },
    shortDesc: { es: "Hombre · 40-46 · Oficio", en: "Man · 40-46 · Trade" },
    gender: "m",
    ageRange: "40-46",
    ageBucket: "40s",
    phenotype: { es: "Latino mestizo", en: "Latino mestizo" },
    archetype: { es: "Maestro de oficio", en: "Master of his trade" },
    category: "oficios",
    toneCommercial: { es: "Cercano confiable", en: "Trustworthy close" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Construcción", en: "Construction" },
      { es: "Hogar / DIY", en: "Home / DIY" },
      { es: "Servicios", en: "Services" },
    ],
    status: "available",
    hue: 22,
    sat: 32,
  },
  {
    code: "YE-W26",
    name: { es: "Profesional de salud", en: "Health professional" },
    shortDesc: { es: "Mujer · 40-46 · Salud", en: "Woman · 40-46 · Health" },
    gender: "f",
    ageRange: "40-46",
    ageBucket: "40s",
    phenotype: { es: "Latina mestiza", en: "Latina mestiza" },
    archetype: { es: "Profesional de salud", en: "Health professional" },
    category: "oficios",
    toneCommercial: { es: "Confiable cálido", en: "Warm trustworthy" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Salud", en: "Health" },
      { es: "Seguros", en: "Insurance" },
      { es: "Servicios públicos", en: "Public services" },
    ],
    status: "available",
    hue: 175,
    sat: 25,
  },

  // ── 50s ──
  {
    code: "YE-M03",
    name: { es: "Senior corporativo", en: "Corporate senior" },
    shortDesc: { es: "Hombre · 50-58 · Autoridad", en: "Man · 50-58 · Authority" },
    gender: "m",
    ageRange: "50-58",
    ageBucket: "50s",
    phenotype: { es: "Latino europeizado", en: "Europeanized Latino" },
    archetype: { es: "Autoridad senior", en: "Senior authority" },
    category: "senior",
    toneCommercial: { es: "Autoridad premium", en: "Premium authority" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Banca corporativa", en: "Corporate banking" },
      { es: "Seguros", en: "Insurance" },
      { es: "Servicios profesionales", en: "Professional services" },
      { es: "Bienestar maduro", en: "Mature wellness" },
    ],
    status: "available",
    hue: 200,
    sat: 15,
  },
  {
    code: "YE-W04",
    name: { es: "Adulta plena", en: "Confident senior" },
    shortDesc: { es: "Mujer · 52-60 · Refinada", en: "Woman · 52-60 · Refined" },
    gender: "f",
    ageRange: "52-60",
    ageBucket: "50s",
    phenotype: { es: "Europeizada", en: "European" },
    archetype: { es: "Adulta plena", en: "Confident senior" },
    category: "senior",
    toneCommercial: { es: "Premium contenido", en: "Premium content" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Banca patrimonial", en: "Wealth banking" },
      { es: "Seguros vida", en: "Life insurance" },
      { es: "Bienestar maduro", en: "Mature wellness" },
    ],
    status: "available",
    hue: 280,
    sat: 20,
  },
  {
    code: "YE-M28",
    name: { es: "Patriarca contemporáneo", en: "Contemporary patriarch" },
    shortDesc: { es: "Hombre · 55-62 · Familiar", en: "Man · 55-62 · Family" },
    gender: "m",
    ageRange: "55-62",
    ageBucket: "50s",
    phenotype: { es: "Latino mestizo", en: "Latino mestizo" },
    archetype: { es: "Patriarca cercano", en: "Approachable patriarch" },
    category: "senior",
    toneCommercial: { es: "Cálido confiable", en: "Warm trustworthy" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Banca patrimonial", en: "Wealth banking" },
      { es: "Seguros", en: "Insurance" },
      { es: "Hogar maduro", en: "Mature home" },
    ],
    status: "available",
    hue: 28,
    sat: 18,
  },
  {
    code: "YE-W14",
    name: { es: "Ejecutiva consolidada", en: "Established executive" },
    shortDesc: { es: "Mujer · 50-56 · Liderazgo", en: "Woman · 50-56 · Leadership" },
    gender: "f",
    ageRange: "50-56",
    ageBucket: "50s",
    phenotype: { es: "Latina europeizada", en: "Europeanized Latina" },
    archetype: { es: "Líder consolidada", en: "Established leader" },
    category: "senior",
    toneCommercial: { es: "Autoridad cálida", en: "Warm authority" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Banca", en: "Banking" },
      { es: "Consultoría", en: "Consulting" },
      { es: "Educación superior", en: "Higher education" },
    ],
    status: "in-campaign",
    hue: 240,
    sat: 22,
  },
  {
    code: "YE-M07",
    name: { es: "Abuelo activo", en: "Active grandfather" },
    shortDesc: { es: "Hombre · 60-66 · Vital", en: "Man · 60-66 · Vital" },
    gender: "m",
    ageRange: "60-66",
    ageBucket: "50s",
    phenotype: { es: "Latino mestizo", en: "Latino mestizo" },
    archetype: { es: "Abuelo vital", en: "Vital grandfather" },
    category: "senior",
    toneCommercial: { es: "Cálido cercano", en: "Warm close" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Salud senior", en: "Senior health" },
      { es: "Turismo", en: "Tourism" },
      { es: "Banca patrimonial", en: "Wealth banking" },
    ],
    status: "available",
    hue: 18,
    sat: 24,
  },
  {
    code: "YE-W23",
    name: { es: "Madre referente", en: "Reference mother" },
    shortDesc: { es: "Mujer · 50-56 · Familiar", en: "Woman · 50-56 · Family" },
    gender: "f",
    ageRange: "50-56",
    ageBucket: "50s",
    phenotype: { es: "Latina mestiza", en: "Latina mestiza" },
    archetype: { es: "Madre referente", en: "Reference mother" },
    category: "familiar",
    toneCommercial: { es: "Cotidiano cálido", en: "Warm everyday" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Salud", en: "Health" },
      { es: "Hogar", en: "Home" },
      { es: "Banca familiar", en: "Family banking" },
    ],
    status: "available",
    hue: 350,
    sat: 28,
  },
  {
    code: "YE-M02",
    name: { es: "Maestro de obra", en: "Master craftsman" },
    shortDesc: { es: "Hombre · 50-58 · Oficio", en: "Man · 50-58 · Trade" },
    gender: "m",
    ageRange: "50-58",
    ageBucket: "50s",
    phenotype: { es: "Latino mestizo", en: "Latino mestizo" },
    archetype: { es: "Maestro de oficio", en: "Master craftsman" },
    category: "oficios",
    toneCommercial: { es: "Cercano confiable", en: "Trustworthy close" },
    market: ["CL", "LATAM"],
    suggestedUses: [
      { es: "Construcción", en: "Construction" },
      { es: "DIY / Hogar", en: "DIY / Home" },
      { es: "Industria", en: "Industry" },
    ],
    status: "available",
    hue: 32,
    sat: 30,
  },
];

// ── Project mock ──
export const PROJECT_SAMSUNG: ProjectConfig = {
  slug: "samsung-galaxy-q1-2026",
  name: "Samsung Galaxy Q1 2026",
  client: "BBDO Chile",
  market: "Chile",
  categoryEs: "Tecnología",
  maxTalents: 10,
  maxExclusive: 3,
  rightsDurationMonths: 12,
  startDate: "2026-04-30",
  status: "active",
};

export const PROJECTS: ProjectConfig[] = [PROJECT_SAMSUNG];

/**
 * Lista de emails con acceso al modulo Talent en Fase 1 (mock).
 * En Fase 2 se reemplaza por: query a `projects WHERE contact_email = ? AND status = 'active'`.
 */
export const TALENT_CLIENT_EMAILS: string[] = [
  "test@bbdo.cl",
  // Email del owner para QA
  "milivoy@yutro.cl",
  "yutrodimitri@gmail.com",
];

/** Devuelve true si el usuario tiene al menos un proyecto Talent activo asignado. */
export function userHasTalentAccess(email: string | null | undefined): boolean {
  if (!email) return false;
  return TALENT_CLIENT_EMAILS.includes(email.toLowerCase());
}

/** Lista de proyectos activos asignados a un email — Fase 1 mock. */
export function getProjectsForUser(email: string | null | undefined): ProjectConfig[] {
  if (!userHasTalentAccess(email)) return [];
  return PROJECTS.filter((p) => p.status === "active");
}

export function getProjectBySlug(slug: string): ProjectConfig | undefined {
  return PROJECTS.find((p) => p.slug === slug);
}

export function getTalentByCode(code: string): Talent | undefined {
  return TALENTS.find((t) => t.code === code);
}

/** Catálogo de talents activos del proyecto. */
export function getAvailableTalents(project: ProjectConfig): Talent[] {
  void project;
  return TALENTS;
}

/** Alias semantico — antes se llamaba getCatalogForProject. Mantener por retrocompat. */
export const getCatalogForProject = getAvailableTalents;
